### ISSUE TITLE
Transpiled Python: index data type too small

### ISSUE THREAD

**Issue by Kriechi** [pfusik/qoi-ci#1]
This code to manage pixel indexes:
https://github.com/pfusik/qoi-ci/blob/5ea8fd4a03c1b3ba4831f451e8c2b0eed63c5259/QOI.ci#L88

transpiles into this Python code 
https://github.com/pfusik/qoi-ci/blob/5ea8fd4a03c1b3ba4831f451e8c2b0eed63c5259/transpiled/QOI.py#L57

Notice the `"i"` type code, which is actually a 2-byte value:
https://docs.python.org/3/library/array.html

This causes a `OverflowError: signed integer is greater than maximum` error when encoding images with Alpha, in the form of AARRGGBB 32bit pixel values, here https://github.com/pfusik/qoi-ci/blob/5ea8fd4a03c1b3ba4831f451e8c2b0eed63c5259/transpiled/QOI.py#L83

I think the correct code should use the `"l"` type code to get a 4-byte value. 
Using `"l"`, I can successfully encode my image without error.

**Comment by pfusik** [comment]
Thanks for the report!

The table you linked says "*Minimum* size in bytes" and the "C Type" is `signed int` which is 4-byte on all modern machines.
So `"i"` is 4-byte, but signed.
Since `pixels` is an array of *signed* ints, it should contain signed values.
You can convert as follows:

    signedArgb = (unsignedArgb ^ (1 << 31)) - (1 << 31)

Let me know if that works for you!
The typed languages will do the type checking for you. I plan to implement type annotations for Python.

`"l"` works on Linux and macOS, where it is 8-byte. However, on Windows it is 4-byte.

**Comment by Kriechi** [comment]
I'm currently working QImage's, which can be encoded in different formats:
https://doc.qt.io/qtforpython-5/PySide2/QtGui/QImage.html#PySide2.QtGui.PySide2.QtGui.QImage.Format
Which one would match your encoding expectation?

I've reverted my `l` to `i` change, and encoded each pixel with your convert formula: it seems to work on macOS!
Thanks!

**Comment by pfusik** [comment]
Yes, it's `QImage.Format_ARGB32`. I'm not satisfied with the signed representation of pixels in `qoi-ci`, but Java has no unsigned types.

For best performance, consider something similar to:

    pixels = array.array("i", snapshot.constBits())
