### ISSUE TITLE
Gimp hangs if qoi file double-clicked in Windows 10

### ISSUE THREAD

**Issue by w3sz** [pfusik/qoi-ci#2]
The plug-in works fine with gimp in windows 10 if a qoi file is opened from within gimp.  I have specified gimp as the default application for qoi files.  But if one attempts to open a qoi file by left-clicking on the file name (or right clicking and then selecting "open"), then gimp fails to open, with a blank windows console displayed instead.

Initially I thought the problem might be that I was using an old version of gimp (2.10.04);  at that point the "stuck" console window would display a missing fast-path babl conversion detected warning instead of being blank.

Then I installed the latest version of gimp 2.10.30 and after doing that, both before and after reinstalling the qoi plug-in I get the blank console window if I left double-click (or right click and then selecting "open") on a qoi file.  QOI files still open correctly if I open them from within gimp.

**Comment by pfusik** [comment]
I don't reproduce this problem using:
- GIMP 2.10.30
- `qoi-ci-1.1.0-win32.msi`
- Windows 21H2

How did you create the file type association? I double-clicked a QOI file in Windows Explorer, selected GIMP and "Always use this app to open .qoi files".

Can you open other file types this way? (e.g. PNG)

Is there some particular QOI file that has this problem?

What happens if you run GIMP from the command line with the QOI file name as an argument?

**Comment by pfusik** [comment]
Closing this ticket because of no response from @w3sz for 3+ months.
